language: elixir

addons:
  postgresql: "9.5"

env:
  global:
    - MIX_ENV=test

elixir: 1.4
otp_release: 20.0

matrix:
  include:
    - elixir: 1.3
      otp_release: 19.3
  allow_failures:
    - elixir: 1.3
      otp_release: 19.3

before_install:
  - cp config/travis.exs config/test.exs
  - mix local.rebar --force

before_script:
  - mix do ecto.create, ecto.migrate
